### PR TITLE
Q14 wps leds SW-3290

### PR DESCRIPTION
**Pull request by nandishminim**
modified the leds.sh script to add the Q14 WPS led reuirement

### CODE REVIEW

**Review by bmastbergen — CHANGES_REQUESTED** [review]
we are missing changes to the led_wlan and led_wlan_off functions for Q14 here.  Those will be called from /etc/rc.button/wps.  As we discussed, its likely that for the Q14 the led_wlan function can just call led_boot and the led_wlan_off function can just call led_off

**Comment by nandishminim** [comment]
> we are missing changes to the led_wlan and led_wlan_off functions for Q14 here. Those will be called from /etc/rc.button/wps. As we discussed, its likely that for the Q14 the led_wlan function can just call led_boot and the led_wlan_off function can just call led_off

i did, like above and observed that after the timeout leds will be off and not showing proper state, with $state change it restores to previous state before the wps button was pressed.  please give your feedback if required i will add LED_OFF itself

**Comment by nandishminim** [comment]
modified the scrpit and added the q14 requirement in led_wan

**Comment by nandishminim** [comment]
can you please review the changes

**Review by bmastbergen — APPROVED** [review]

**Pull request merged**
