### PR TITLE
added 39_upnp_enable_config to uci_defaults to enable upnp at poweron…

### PR DESCRIPTION
**Pull request by nandishminim**
added the 39_upnp_enable config to uci_defaults please approve it

### CODE REVIEW

**Review by bmastbergen — COMMENTED** [review]
not needed, BUT we do need to add the '/etc/init.d/miniupnpd restart' to files/lede_generic/restart_config.sh in unum-sdk

**Comment by nandishminim** [comment]
removed the restart command in uci defaults

**Review by bmastbergen — COMMENTED** [review]
NAK.  Firmware does not need to enable miniupnpd.  The cloud will push down the uci config to enable it when the user turns it on

**Comment by nandishminim** [comment]
shall we reject this PR so no changes from our side

**Comment by nandishminim** [comment]
as server will control the enabling or disabling of upnp so i am closing this PR

**Pull request closed without merging**
